# This is a basic workflow to help you get started with Actions

name: build

# Controls when the workflow will run
on:

  # watch:
    # types: [started]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.1        
      
      - name: Build linux kernel
        run: bash build.sh
      
      - name: Get date
        run: echo "date=$(date +'%m/%d_%Y_%H/%M')" >> $GITHUB_ENV
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          path: linux/arch/x86/boot/bzImage
      
      # - uses: "marvinpinto/action-automatic-releases@latest"
      #   with:
      #     repo_token: "${{ secrets.REPO_TOKEN }}"
      #     files: linux/arch/x86/boot/bzImage  
      #     prerelease: false
      #     automatic_release_tag: ${{ env.date }}
